### ISSUE TITLE
Wrong message it is showed when I enter long decimal value

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/ido-ux#299] opened 2021-03-24 20:33 UTC
I guess the message should be different. Something like: "You can use only XX digits"

If I enter this value: 0.0312345678987654321
Then I see this error message: "Amount must be bigger than 0.01"
If I enter just one digit less, then the message disappears. 

![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/ca13d08b-2d52-43c3-b280-d7d415d88ab2)

**Comment by gabitoesmiapodo** [comment] 2021-04-07 20:14
Duplicate of https://github.com/gnosis/ido-ux/issues/231, closing.

**Closed by gabitoesmiapodo** 2021-04-07 20:14 UTC
Labels: FE, bug, low priority
