### ISSUE TITLE
Chrome + Metamask user can't submit transactions 

### ISSUE THREAD

**Issue by Rafanator** [gnosis/ido-ux#451] opened 2021-04-07 11:17 UTC
User could not submit transaction for approve. 

- Metamask showed the tx's as approved, but they did not show on Etherscan:

![gaissues](https://user-images.githubusercontent.com/26544214/113857910-62eb8e00-97a3-11eb-87f0-d456edf0f056.png)

- Console error:

![GAissue](https://user-images.githubusercontent.com/26544214/113857948-71d24080-97a3-11eb-9e63-431086278a99.png)

- Console warning:

![warnings](https://user-images.githubusercontent.com/26544214/113858008-7f87c600-97a3-11eb-9ff6-557919e1024f.png)

The user had no issues with Firefox.

**Comment by ramirotw** [comment] 2021-06-07 12:14
@elena-zh were you able to reproduce this?

**Comment by elena-zh** [comment] 2021-06-07 12:15
@ramirotw , no, I was not able to reproduce it. 
@Rafanator , is the issue still reproducible for you?

**Comment by Rafanator** [comment] 2021-06-07 12:28
Hi. I just tried and wasn't able to reproduce it. 

Also, I no longer work for Gnosis :D So please remove me from this repo. 

It was nice working with all of you!

**Comment by josojo** [comment] 2021-06-07 12:34
@Rafanator same!

you are just a normal github user for this repo.

**Comment by elena-zh** [comment] 2021-06-07 12:34
I'm closing the issue then as it is no longer reproducible. 
@Rafanator same! And sorry for bothering you!

**Closed** 2021-06-07 12:34 UTC
Labels: bug
