### ISSUE TITLE
[auction details] Allow List Contract and Signer Address links point to mainnet all the time

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#605] opened 2021-05-21 07:56 UTC
1. open app
2. open some auction (ie, some auction in rinkeby) https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=100&chainId=4#topAnchor
3. click More details
4. follow link near Allow List Contract 

**Result**: https://etherscan.io/address/0x7c882f296335734b958b35da6b2595fa00043ae9
**Exp.result:** https://rinkeby.etherscan.io/address/0x7c882f296335734b958b35da6b2595fa00043ae9

**see the same for Signer Address** : https://etherscan.io/address/0xd176effb29f9a80f06db43ecfa4ef428370ed673

Moreover, these links navigate to the etherscan when an auction is opened in **xDAI network**. 
They should navigate to `https://blockscout.com/xdai/mainnet/address/.......`

**Comment by ramirotw** [comment] 2021-06-07 10:16
Removing the medium priority as this only affects the development environment

**Comment by elena-zh** [comment] 2021-06-07 11:22
@ramirotw , I would leave the med priority due to the issue is related to the xDAI chain as well. 
Links navigate to Etherscan instead of Blockscout, and that should be fixed.

**Closed** 2021-07-21 17:12 UTC
Labels: QA, bug, medium priority
