### ISSUE TITLE
reconnect to xDai automatically, without clicking 'Connect to a wallet'

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#611] opened 2021-05-24 19:25 UTC
open app
click Connect to a wallet and connect to MetaMask, rinkeby network
switch to xDai network in Metamask

Result: app shows 'Connect to a wallet'
Exp.result: reconnect to xDai network automatically

to compare, if I am connected to Mainnet and switch to rinkeby, it does not require to click Connect to a wallet when select rinkeby in MetaMask

**Comment by elena-zh** [comment] 2021-06-01 07:56
Duplicate of #303
Closed

**Closed** 2021-06-01 07:57 UTC
Labels: duplicate, enhancement, low priority
