### ISSUE TITLE
Shows different decimals on the prices - Current price vs Max bidding price

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/ido-ux#575] opened 2021-05-19 11:37 UTC
Showing different decimals

Link: https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=21&chainId=4#topAnchor

Screenshot:
![image.png](https://images.zenhubusercontent.com/5e664bce015a7a82381ccd09/e628f56c-e099-4c76-985b-c4c899d65153)

**Comment by josojo** [comment] 2021-05-19 12:17
The price is suggested in such a way that one bids a little bit more than the current price, in order to be included in the auction. I think its all fine. Which behaviour would recommend?

**Comment by ramirotw** [comment] 2021-06-07 10:11
Removing the medium priority as for now this is an intended behavior. Maybe this should be reviewed as a UX improvement if more users mentions it.

**Comment by elena-zh** [comment] 2021-06-08 13:36
I think that it works as intended due to the very beginning prices in the Max bidding price fields are displayed according to the formula
Current price+0.1%
So, 143.3+0.1% = 143.44 (143.4)

I'd rather close this issue.

**Comment by josojo** [comment] 2021-06-08 14:31
Yes, let's close it

**Closed by josojo** 2021-06-08 14:31 UTC
Labels: QA, UX, low priority
