### ISSUE TITLE
Include "Current Price" in chart's x-axis

### ISSUE THREAD

**Issue by Rafanator** [gnosis/ido-ux#468] opened 2021-04-08 06:37 UTC
I got the following feedback from a power user to include "Current Price" in chart's x-axis, where the arrow points in this example: 

![image_2021-04-07_14-57-24](https://user-images.githubusercontent.com/26544214/113979508-a0085c80-9845-11eb-9b53-8dc012726050.png)

**Comment by elena-zh** [comment] 2021-04-08 15:25
Might be a duplicate of #406

**Comment by ramirotw** [comment] 2021-06-07 12:27
@alongoni this could be tackled as a solution for #574.

Displaying the current price in the x-axis all the time could be problematic as it depends on the viewport's width and it can overlap with other values. Maybe showing the current price value in the suggested legend improvement could be an option.

**Comment by elena-zh** [comment] 2021-07-05 08:17
I'm closing the issue as solution is provided in #574

**Closed** 2021-07-05 08:17 UTC
Labels: UX, enhancement, low priority
